name: Sync to Personal Mirror

on:
  push:
    branches: [ "main" ]

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout University Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Mirror (Manual)
        run: |
          git config --unset-all http.https://github.com/.extraheader
          
          git config --global user.email "sudheeradilum@gmail.com"
          git config --global user.name "sudheera2003"
          
          git remote add mirror "https://sudheera2003:${{ secrets.API_TOKEN_GITHUB }}@github.com/sudheera2003/fd-group-58-mirror.git"
          
          git push mirror main --force